

void     Timebase_Struct_Init(void);
void     Timebase_Timer_Config(uint16_t UpdateRateHz);
void     Timebase_Init(uint16_t UpdateRateHz);
void     Timebase_Wait_Unit_Time(void);
uint8_t  Timebase_Total_Tokens_Executing(void);
void     Timebase_Add_Token(void);
void     Timebase_Remove_Token(void);
void     Timebase_Remove_All_Tokens(void);
void     Timebase_Set_Status_Busy(void);
void     Timebase_Clear_Status_Busy(void);
uint8_t  Timebase_Check_Busy_Status(void);
void     Timebase_Set_Timer_Reset_Request_Status(void);
void     Timebase_Clear_Timer_Reset_Request_Status(void);
uint8_t  Timebase_Check_Timer_Reset_Request_Status(void);
uint32_t Timebase_Get_SubSeconds(void);
uint32_t Timebase_Get_Seconds(void);
void     Timebase_Set_SubSeconds(uint32_t value);
void     Timebase_Set_Seconds(uint32_t value);
void     Timebase_Reset_SubSeconds(void);
void     Timebase_Reset_Seconds(void);
void     Timebase_Set_DownCounter_Status(uint8_t window);
void     Timebase_Clear_DownCounter_Status(uint8_t window);
uint8_t  Timebase_Check_DownCounter_Status(uint8_t window);
void     Timebase_Pause_DownCounter(uint8_t window);
void     Timebase_Resume_DownCounter(uint8_t window);
uint8_t  Timebase_Check_DownCounter_Freeze_Status(uint8_t window);
void     Timebase_Securely_Set_DownCounter_Seconds(uint8_t window, uint32_t value);
void     Timebase_Forcefully_Set_DownCounter_Seconds(uint8_t window, uint32_t value);
void     Timebase_Reset_DownCounter(uint8_t window);
uint32_t Timebase_Get_DownCounter_Seconds(uint8_t window);
void     Timebase_Update_DownCounters(void);
void     Timebase_Reset_DownCounters(void);
void     Timebase_Safely_Reset_Timer(void);
void     Timebase_ISR_Executables(void);